<a href="https://colab.research.google.com/github/Temur0122/NumPy_kutubxonasi_bilan_ishlash/blob/main/1_NumPy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy kutubxonasini chaqirib olish

In [1]:
import numpy as np

# N-o'lchamli massivlarga ishlov berish

# NumPy da massiv yaratishningeng oson yo'llaridan biri bu **Array** funksiyasi yordamida amalga oshiriladi.Va ushbu funksiya har qandayb turdagiketma ket ma'lumotlarniqabul qilib, uni yangi NumPy arrayiga o'girib beradi.

In [2]:
data1 =[2.3, 4, 4, 5, 6] # list
arr1 =np.array(data1) #array1

In [3]:
arr1

array([2.3, 4. , 4. , 5. , 6. ])

# Massiv o'lchami

In [4]:
arr1.ndim # Array1 ning  o'lchami

1

# Ikki va undan katta o'lchamli massivlar

In [9]:
data3 = [[[1, 2, 3], [4, 5, 6], [7, 8, 9] ] ]
arr3 =np.array(data3)

In [10]:
arr3.ndim

3

In [11]:
arr3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

# Shape, size metodlari

***shape*** metodi massivningqator va ustunlar sonini ko'rsatsa, ***size*** esa massivlardagi elementlar sonini namoyon qiladi.

In [12]:
arr3.shape # qator va ustunlar soni ko'rsatadi (q, u)

(1, 3, 3)

In [13]:
arr3.size # elementlar soni

9

# N-o'lchovli massiv yaratishning boshqa usullari
***Zeros*** ,***ones*** funksiyalari yordamida massiv yaratish

In [16]:
arr4 = np.zeros((3, 5)) # faqat nollardan iborat 3x5 lik massiv
arr4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
arr5 = np.ones((4, 6)) # faqat 1 lardan iborat 4x6 lik massiv
arr5

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

***arange*** funksiyasi yordamida yaratish

In [18]:
arr6 = np.arange(2, 22, 2) # 2 dan 22 gacha bo'lgan sonlarni 2 qadamdan massivga joylab beradi
arr6

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [19]:
arr7 = np.arange(10) # 0 dan 10 gacha bo'lgan sonlarni 1 qadamdan massivga joylab beradi
arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])