<a href="https://colab.research.google.com/github/Temur0122/NumPy_kutubxonasi_bilan_ishlash/blob/main/_4_Boolean_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
#ismlar
names = np.array(['Hasan', 'Husan', 'Mirzo', 'Hasan', 'Husan', 'Elyor', 'Temur'])
names

array(['Hasan', 'Husan', 'Mirzo', 'Hasan', 'Husan', 'Elyor', 'Temur'],
      dtype='<U5')

In [3]:
#data
data =np.random.randn(7,4)
data

array([[ 0.2818425 , -0.19792183, -1.33499859,  0.15211133],
       [-0.49905261,  0.46871892,  0.64915048,  0.94069089],
       [ 1.32757257,  0.36114085, -0.03382893,  0.80819897],
       [-0.38233462, -0.80905682,  0.57788211, -1.27530872],
       [ 0.50998942, -1.14951664,  2.46754853, -1.52315524],
       [-0.60556766,  1.33574951, -0.89068643,  0.89578902],
       [ 0.31752963, -0.9271461 , -0.83703455, -0.19501383]])

In [4]:
names == 'Hasan'

array([ True, False, False,  True, False, False, False])

In [5]:
data[names == 'Hasan'] # Hasanga tegishli ma'lumotlarni ajratib olish

array([[ 0.2818425 , -0.19792183, -1.33499859,  0.15211133],
       [-0.38233462, -0.80905682,  0.57788211, -1.27530872]])

In [6]:
data[names == 'Hasan', 2:] #Hasanga tegishli oxirgi ikki ustundagi ma'lumotlarni kesib olish

array([[-1.33499859,  0.15211133],
       [ 0.57788211, -1.27530872]])

In [7]:
data[names != 'Hasan'] # (!=) Hasandan tashqari barcha elementlarni ajratib oladi

array([[-0.49905261,  0.46871892,  0.64915048,  0.94069089],
       [ 1.32757257,  0.36114085, -0.03382893,  0.80819897],
       [ 0.50998942, -1.14951664,  2.46754853, -1.52315524],
       [-0.60556766,  1.33574951, -0.89068643,  0.89578902],
       [ 0.31752963, -0.9271461 , -0.83703455, -0.19501383]])

In [8]:
data[~(names == 'Hasan')] # (~) Yuqoridagi cell bilan bir xil natijani beradi

array([[-0.49905261,  0.46871892,  0.64915048,  0.94069089],
       [ 1.32757257,  0.36114085, -0.03382893,  0.80819897],
       [ 0.50998942, -1.14951664,  2.46754853, -1.52315524],
       [-0.60556766,  1.33574951, -0.89068643,  0.89578902],
       [ 0.31752963, -0.9271461 , -0.83703455, -0.19501383]])

In [13]:
print(names)

['Hasan' 'Husan' 'Mirzo' 'Hasan' 'Husan' 'Elyor' 'Temur']


In [14]:
print(data)

[[ 0.2818425  -0.19792183 -1.33499859  0.15211133]
 [-0.49905261  0.46871892  0.64915048  0.94069089]
 [ 1.32757257  0.36114085 -0.03382893  0.80819897]
 [-0.38233462 -0.80905682  0.57788211 -1.27530872]
 [ 0.50998942 -1.14951664  2.46754853 -1.52315524]
 [-0.60556766  1.33574951 -0.89068643  0.89578902]
 [ 0.31752963 -0.9271461  -0.83703455 -0.19501383]]


In [15]:
mask = (names == 'Hasan') | (names == 'Husan')
mask

array([ True,  True, False,  True,  True, False, False])

In [16]:
data[mask]

array([[ 0.2818425 , -0.19792183, -1.33499859,  0.15211133],
       [-0.49905261,  0.46871892,  0.64915048,  0.94069089],
       [-0.38233462, -0.80905682,  0.57788211, -1.27530872],
       [ 0.50998942, -1.14951664,  2.46754853, -1.52315524]])

In [17]:
data

array([[ 0.2818425 , -0.19792183, -1.33499859,  0.15211133],
       [-0.49905261,  0.46871892,  0.64915048,  0.94069089],
       [ 1.32757257,  0.36114085, -0.03382893,  0.80819897],
       [-0.38233462, -0.80905682,  0.57788211, -1.27530872],
       [ 0.50998942, -1.14951664,  2.46754853, -1.52315524],
       [-0.60556766,  1.33574951, -0.89068643,  0.89578902],
       [ 0.31752963, -0.9271461 , -0.83703455, -0.19501383]])

In [18]:
data[data<0]

array([-0.19792183, -1.33499859, -0.49905261, -0.03382893, -0.38233462,
       -0.80905682, -1.27530872, -1.14951664, -1.52315524, -0.60556766,
       -0.89068643, -0.9271461 , -0.83703455, -0.19501383])

In [19]:
data[data<0] = 0
data

array([[0.2818425 , 0.        , 0.        , 0.15211133],
       [0.        , 0.46871892, 0.64915048, 0.94069089],
       [1.32757257, 0.36114085, 0.        , 0.80819897],
       [0.        , 0.        , 0.57788211, 0.        ],
       [0.50998942, 0.        , 2.46754853, 0.        ],
       [0.        , 1.33574951, 0.        , 0.89578902],
       [0.31752963, 0.        , 0.        , 0.        ]])