<a href="https://colab.research.google.com/github/Temur0122/NumPy_kutubxonasi_bilan_ishlash/blob/main/Chiziqli_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np




In [23]:
x =np.arange(6).reshape(2,3)
x

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
y =np.arange(6).reshape(3,2)
y

array([[0, 1],
       [2, 3],
       [4, 5]])

In [25]:
x.dot(y)


array([[10, 13],
       [28, 40]])

In [26]:
np.dot(x,y)

array([[10, 13],
       [28, 40]])

In [27]:
np.dot(y,x)

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])