<a href="https://colab.research.google.com/github/Temur0122/NumPy_kutubxonasi_bilan_ishlash/blob/main/Fayllar_bilan_ishlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np




In [11]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.save('data', arr) # fayl qilib saqlash

In [14]:
arr2 = np.load('data.npy')
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr1 =np.arange(21)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [16]:
np.savez('arrays', a=arr, b=arr1)

In [18]:
arrays =np.load('arrays.npz')

In [19]:
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [21]:
np.savez_compressed('array_comp', a= arr, b=arr1)# fayylarni siqib saqlaydi