<a href="https://colab.research.google.com/github/Temur0122/NumPy_kutubxonasi_bilan_ishlash/blob/main/Mantiqiy_shart_operatori_where.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
xarr =np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr =np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [3]:
cond =np.array([True, False ,True, True, False])


In [4]:
result = np.where(cond ,xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [7]:
arr = np.random.randn(4,4)
arr

array([[ 1.27302616,  1.27157534, -0.29665655, -0.77064645],
       [-0.73540152,  0.34736491,  1.78906608, -0.65686921],
       [-0.32371361,  0.08053556,  1.30270401, -1.30339588],
       [-0.57531463,  0.94680738, -0.05964823, -0.24231746]])

In [8]:
results = np.where(arr<0 , -2 ,2)
results

array([[ 2,  2, -2, -2],
       [-2,  2,  2, -2],
       [-2,  2,  2, -2],
       [-2,  2, -2, -2]])