<a href="https://colab.research.google.com/github/Temur0122/NumPy_kutubxonasi_bilan_ishlash/blob/main/Sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np



In [15]:
arr = np.random.rand(4)
arr

array([0.1939532 , 0.97788013, 0.65777954, 0.91591345])

In [17]:
arr.sort()
arr


array([0.1939532 , 0.65777954, 0.91591345, 0.97788013])

In [19]:
rev_arr = -np.sort(-arr)
rev_arr

array([0.97788013, 0.91591345, 0.65777954, 0.1939532 ])

In [20]:
arr2d = np.random.randn(2,4)
arr2d

array([[ 1.32401458,  0.05151173,  0.83739495, -0.73499841],
       [-1.02539186,  1.22125741,  1.71986487,  0.06814996]])

In [22]:
row_srt= np.sort(arr2d , axis= 0)
row_srt



array([[-1.02539186,  0.05151173,  0.83739495, -0.73499841],
       [ 1.32401458,  1.22125741,  1.71986487,  0.06814996]])

In [23]:
row_srt.sort(axis = 1)

In [24]:
row_srt

array([[-1.02539186, -0.73499841,  0.05151173,  0.83739495],
       [ 0.06814996,  1.22125741,  1.32401458,  1.71986487]])