<a href="https://colab.research.google.com/github/Temur0122/NumPy_kutubxonasi_bilan_ishlash/blob/main/Sum_mean_math_statik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
arr = np.random.randn(5,4)
arr

array([[ 1.10683056,  1.83695089, -1.84744965, -0.82206427],
       [-1.4486224 , -0.55230369, -0.20622792, -0.54271564],
       [ 1.11069867, -1.59577956,  0.56888719,  0.03499344],
       [ 1.47570216, -0.90641569,  0.59896207, -0.4285479 ],
       [ 1.18772697,  0.77201442,  0.49538857,  0.9272848 ]])

In [4]:
arr.sum()

1.7653130166334619

In [5]:
arr.sum(axis = 1) # Qator bo'yicha yig;indisi

array([ 0.27426753, -2.74986965,  0.11879975,  0.73970064,  3.38241476])

In [6]:
arr.sum(axis = 0) # Ustun bo'yicha yig'indisi


array([ 3.43233596, -0.44553363, -0.39043974, -0.83104958])

In [7]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [9]:
data.mean() # o'rta arifmetik hisoblaydi

2.0

In [10]:
np.mean(arr, axis =1) # qator bo'yacha o'rta arifmetigi

array([ 0.06856688, -0.68746741,  0.02969994,  0.18492516,  0.84560369])

In [11]:
data

array([0, 1, 2, 3, 4])

In [12]:
data.cumsum()

array([ 0,  1,  3,  6, 10])