<a href="https://colab.research.google.com/github/Temur0122/NumPy_kutubxonasi_bilan_ishlash/blob/main/Universal_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Unary funksiyalar(bitta argument qabul qiladigan funksiyalar)


```
# sqrt, square, exp, log, modf, sign, isnan

```
funksiyalarni ko`rib chiqamiz


In [2]:
import numpy as np
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# `sqrt` - massivning barcha elementlarini ildizini hisoblaydi

In [4]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

`square`-Massivning barcha elementlarini kvadratini hisoblaydi

In [5]:
np.square(arr)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

`exp`- massivning har bir elementi uchun e^ hisoblaydi

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

`log`- massivning har bir elementi uchun logarifm e hisoblaydi

In [7]:
np.log(arr[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

`modf`- massiv elementlari haqiqiy son bo'lsa ularni qoldiq qismini alohida butun qismini alohida massivga joylab beruvchi funksiya

In [3]:
arr1 = np.random.randn(6)
arr1

array([ 1.06656348,  1.56502137,  1.87865556, -0.64107397, -1.6612109 ,
        0.48998672])

In [4]:
qoldiq, butun = np.modf(arr1)
print(qoldiq)
print(butun)


[ 0.06656348  0.56502137  0.87865556 -0.64107397 -0.6612109   0.48998672]
[ 1.  1.  1. -0. -1.  0.]


`sign`-  massiv elementlari qiymati manfiy bo'lsa `-1`va aksincha musbat bo'lsa `1` ni qaytaradi

In [5]:
np.sign(arr1)

array([ 1.,  1.,  1., -1., -1.,  1.])

`isnan`-massivning elementlarida NaN(bo'sh) ma'lumoti bo'lsa `True` qaytaradiva aksincha esa `False` ni qaytaradi

In [6]:
np.isnan(arr1)

array([False, False, False, False, False, False])

In [7]:
arr1[0] = np.NAN

In [8]:
arr1

array([        nan,  1.56502137,  1.87865556, -0.64107397, -1.6612109 ,
        0.48998672])

In [9]:
np.isnan(arr1)

array([ True, False, False, False, False, False])

# Binary funksiyalar (ikkita argument qabul qiluvchi funksiyalar)

In [10]:
arr2 =np.random.randn(7)
arr3 =np.random.randn(7)
arr2

array([ 0.07382997, -0.15248027, -1.54538827,  1.66430861, -0.09643087,
       -0.830726  ,  0.64706216])

In [11]:
arr3

array([-0.86338898,  0.41674285, -0.69601489,  0.45445589,  1.97689523,
       -0.72854012, -1.09125619])

`add`- ikkita massivning elementlarini mos ravishda qo'shib beradi



In [12]:
np.add(arr2, arr3)

array([-0.78955901,  0.26426258, -2.24140316,  2.1187645 ,  1.88046437,
       -1.55926612, -0.44419403])

`multiply`-ikkita massivning mos elementlarini ko'paytiradi

In [13]:
arr2

array([ 0.07382997, -0.15248027, -1.54538827,  1.66430861, -0.09643087,
       -0.830726  ,  0.64706216])

In [14]:
arr3

array([-0.86338898,  0.41674285, -0.69601489,  0.45445589,  1.97689523,
       -0.72854012, -1.09125619])

In [15]:
np.multiply(arr2, arr3)

array([-0.06374398, -0.06354506,  1.07561324,  0.75635486, -0.19063372,
        0.60521722, -0.70611059])

`maximum`- ikkita massivning mos elementlarini taqqoslab ulardan kattasini qaytaradi.

In [16]:
np.maximum(arr2, arr3)

array([ 0.07382997,  0.41674285, -0.69601489,  1.66430861,  1.97689523,
       -0.72854012,  0.64706216])